[tool.pylint.messages_control]

disable = [
    "invalid-name",
    "too-few-public-methods",
    "too-many-arguments",
    "redefined-outer-name",
    "global-variable-undefined",
    "unused-variable",
    "unused-import",
    "ungrouped-imports",
]

[tool.black]
line_length = 88
target_version = ["py310"]
skip_string_normalization = true

[tool.isort]
multi_line_output = 3
length_sort = true
profile = "black"
