[tool.pylint.messages_control]

disable = [
    "invalid-name",
    "too-few-public-methods",
    "too-many-arguments",
    "redefined-outer-name",
    "global-variable-undefined",
    "unused-variable",
    "unused-import",
    "ungrouped-imports",
    "missing-module-docstring",
    "too-many-locals",
    "expression-not-assigned",
    "useless-return",
    "missing-function-docstring",
    "line-too-long",
    "not-context-manager",
    "redefined-builtin",
    "missing-timeout",
]

[tool.black]
line_length = 88
target_version = ["py310"]
skip_string_normalization = true
force-exclude = '''
/(
    scripts
| integraton-test
| \.terraform
)/
| pyproject\.toml
| Dockerfile
| Makefile
| README.md
| main\.tf
| variables\.tf
| \.gitignore
| \.terraform\.lock\.hcl
'''

[tool.isort]
multi_line_output = 3
length_sort = true
profile = "black"
