# config file version
apiVersion: 1

# list of datasources to insert/update
# available in the database
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    database: homework
    user: postgres
    secureJsonData:
      password: 'qwerty123'
    jsonData:
      sslmode: 'disable'